name = "mutantsolver"
description = ""
version = "0.1.0-dev"

authors = ["krispyensign"]
maintainers = ["krispyensign <futralj@gmail.com>"]
maintainers-logins = ["krispyensign"]
licenses = "Apache-2.0"
website = ""
tags = []

executables = ["mutantsolver"]

[[depends-on]]
aws = "^24.0.0"

[[depends-on]]
simple_logging = "^1.2.0"

[[depends-on]]
gnatcoll = "^24.0.0"

[[depends-on]]
ada_toml = "~0.5.0"
