name: Ada (GNAT)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    name: CI on linux

    runs-on: debian-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: alire-project/setup-alire
      uses: alire-project/setup-alire@v4

    - name: Install toolchain
      run: |
        alr --non-interactive settings --global --set toolchain.assistant false
        alr --non-interactive toolchain --select gnat_native
        alr --non-interactive toolchain --select gprbuild

    - name: Build and run
      run: |
        alr --non-interactive build
