name: Ada (GNAT)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    name: CI on linux

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: alire-project/setup-alire
      uses: alire-project/setup-alire@v4
      with:
        version: 2.1.0
        toolchain: gnat_native gprbuild

    - name: Build and run
      run: |
        alr --non-interactive build
